# Generated by Django 3.1.7 on 2021-11-05 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211104_1623'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StravaToken',
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
