# Generated by Django 3.1.7 on 2021-11-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_breakfast_dinner_kcalgoal_lunch_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='carbs',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='fats',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='kcal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='proteins',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
