# Generated by Django 3.1.7 on 2021-11-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211119_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentUserFoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=200)),
            ],
        ),
    ]
