# Generated by Django 3.1.7 on 2021-11-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_recentuserfoods'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentuserfoods',
            name='grams',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recentuserfoods',
            name='kcal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
