# Generated by Django 3.1.7 on 2021-11-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20211121_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentuserfoods',
            name='product_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
