# Generated by Django 3.1.7 on 2021-11-21 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_products_product_is'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_is',
            new_name='product_id',
        ),
    ]
