# Generated by Django 3.1.7 on 2021-11-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20211121_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdailyfood',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
