# Generated by Django 3.1.7 on 2021-12-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_userdailyfood_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdailyfood',
            name='product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
