# Generated by Django 3.1.7 on 2021-12-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_userdailyfood_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='kcalgoal',
            name='carbs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kcalgoal',
            name='fibers',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kcalgoal',
            name='proteins',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
