# Generated by Django 3.1.7 on 2021-12-26 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20211226_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kcalgoal',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='kcalgoal',
            name='fibers',
        ),
        migrations.RemoveField(
            model_name='kcalgoal',
            name='proteins',
        ),
    ]
