# Generated by Django 3.1.7 on 2022-01-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_kcalgoal_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='kcal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recentuserfoods',
            name='kcal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userdailyfood',
            name='kcal',
            field=models.FloatField(),
        ),
    ]
