# Generated by Django 3.1.7 on 2022-01-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20220129_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentuserfoods',
            name='product_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userdailyfood',
            name='product_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
