# Generated by Django 3.1.7 on 2022-01-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20220129_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentuserfoods',
            name='carbs',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recentuserfoods',
            name='fats',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recentuserfoods',
            name='fibers',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recentuserfoods',
            name='proteins',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recentuserfoods',
            name='sugars',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
