# Generated by Django 3.1.7 on 2021-11-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='weight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
