# Generated by Django 3.1.7 on 2021-11-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0002_userdetails_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('activity_type', models.CharField(blank=True, max_length=200)),
                ('start_date_local', models.DateTimeField(auto_now_add=True)),
                ('elapsed_time', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('distance', models.IntegerField()),
            ],
        ),
    ]
