# Generated by Django 3.1.7 on 2021-11-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0004_activity_user_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
