# Generated by Django 3.1.7 on 2021-11-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0005_activity_activity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='user_key',
            field=models.CharField(max_length=50),
        ),
    ]
