# Generated by Django 3.1.7 on 2021-11-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0008_auto_20211116_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
