# Generated by Django 3.1.7 on 2022-01-26 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0010_auto_20220126_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
