# Generated by Django 3.1.7 on 2022-01-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0011_auto_20220126_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
