# Generated by Django 3.1.7 on 2022-01-26 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0012_auto_20220126_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='description',
        ),
    ]
