# Generated by Django 3.1.7 on 2022-01-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0013_remove_activity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='user_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
