# Generated by Django 3.1.7 on 2022-01-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0015_auto_20220126_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='long',
        ),
        migrations.AddField(
            model_name='activity',
            name='polyline',
            field=models.CharField(blank=True, max_length=10000000000000000000000000, null=True),
        ),
    ]
