# Generated by Django 3.1.7 on 2022-01-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0017_stravatoken_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
