# Generated by Django 3.1.7 on 2022-01-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0018_activity_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
